### ISSUE TITLE
Possible inconsistencies for pulse identifiers when stored using PulseStorage

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#272]
The dictionary interface of PusleStorage in principle allows it to store pulse under a different identifier than the one they were given on pulse construction, thus creating inconsistencies (or "hidden" renames).

**Comment by lumip** [comment]
Resolution: Storing PulseTemplates in PulseStorage under a different identifier should change their identifier in the PulseTemplate as well as in storage. Previous versions stored in PulseStorage under the old identifier should remain unchanged in this case.

**Comment by terrorfisch** [comment]
I see three possibilities:
1. Create a new object with the new identifier (maybe via a new `renamed` method of Serializable). The problem is that it might be unexpected that a following __getitem__ call gives you a different object.
2. Throw an error. The user should call that rename method by himself.
3. Create a Reference like thing. Maybe something like an AbstractPulseTemplate which references the other one on load.

**Comment by lumip** [comment]
This is currently fixed by PR #306 by introducing a method Serializable.renamed(new_identifier) which returns a copy of the original Serializable object with the given new identifier to enable explicit renames and having PulseStorage raise an error (which points to the possibility of renamed()) when attempting to store a PulseTemplate/Serializable under a different identifier than its internal one.

**Comment by terrorfisch** [comment]
Fixed as we throw an exception now.
