### ISSUE TITLE
Documentation Extraction Tool

### ISSUE THREAD

**Issue by lumip** [qutech/qc-toolkit#49]
To extract a documentation of the Toolkit I have experimented with doxygen (link) but it is not really optimized for python. It works, but the results look weird, especially since it does not work well with type hints: Each type hint is intepreted as an additional method parameter.
Looking for a better tool I've read of [Sphinx](http://sphinx-doc.org/) which seems to be made for python and I would test it sometime in the future.
Does anyone have experience with commonly used tools for python and knows recommendations/alternatives?

**Comment by hbluhm** [comment]
No experience, but I believe the official Python implementation uses some tool (which might well be Sphinx) and the results look pretty good.

**Comment by pbethke** [comment]
It is sphinx, and it is used by a wide range of python projects from small and large (like django, scipy/numpy, the standard implementation, etc.)

Sphinx docstrings can however make the docstrings a bit markup heavy. Since Sphinx 1.3.1 there is an extension that parses [Google style doc strings](http://google.github.io/styleguide/pyguide.html#Comments), which are both readable in source code and parsable by Sphinx.

Example:
```python
def fetch_bigtable_rows(big_table, keys, other_silly_variable=None):
    """Fetches rows from a Bigtable.

    Retrieves rows pertaining to the given keys from the Table instance
    represented by big_table.  Silly things may happen if
    other_silly_variable is not None.

    Args:
        big_table: An open Bigtable Table instance.
        keys: A sequence of strings representing the key of each table row
            to fetch.
        other_silly_variable: Another optional variable, that has a much
            longer name than the other args, and which does nothing.

    Returns:
        A dict mapping keys to the corresponding table row data
        fetched. Each row is represented as a tuple of strings. For
        example:

        {'Serak': ('Rigel VII', 'Preparer'),
         'Zim': ('Irk', 'Invader'),
         'Lrrr': ('Omicron Persei 8', 'Emperor')}

        If a key from the keys argument is missing from the dictionary,
        then that row was not found in the table.

    Raises:
        IOError: An error occurred accessing the bigtable.Table object.
    """
    pass
```

Additional documentation can still be added in standard reStructured Text markup, just like usual Sphinx (for images, general description and so on).

**Comment by lumip** [comment]
I think that's fine and would create an issue to set up sphinx and adapt the existing docstrings for the future.
